[[block]]
block = "cpu"
format_alt = " $frequency{ $boost|} "
interval = 1

[[block]]
block = "memory"
format = " $icon $mem_used_percents "
format_alt = " $icon_swap $swap_used_percents "
interval = 5

[[block]]
block = "disk_space"
path = "/"
format_alt = " (use $used) "
interval = 60

[[block]]
block = "battery"
format = " $icon  $time"
device = "BAT0"

[[block]]
block = "battery"
format = " $icon  $time"
device = "BAT1"

[[block]]
block = "net"
format = " $icon {$signal_strength $ssid $ip ^icon_net_down$speed_down.eng(prefix:K) ^icon_net_up$speed_up.eng(prefix:K)} "
interval = 5

[[block]]
block = "sound"

[[block]]
block = "notify"

[[block]]
block = "time"
format = " $timestamp.datetime(f:'%a %d-%m %R') "
interval = 60

[icons]
icons = "awesome4"

[theme]
theme = "srcery"
