[[block]]
block = "focused_window"

[[block]]
block = "cpu"
format_alt = " $frequency{ $boost|} "
interval = 5

[[block]]
block = "memory"
format = " $icon $mem_used_percents "
format_alt = " $icon_swap $swap_used_percents "
interval = 5

[[block]]
block = "disk_space"
path = "/"
format_alt = " (use $used) "
interval = 60

[[block]]
block = "battery"
format = " $icon  $time"
device = "BAT0"

[[block]]
block = "net"
format = " $icon {$signal_strength ^icon_net_down$speed_down.eng(prefix:K) ^icon_net_up$speed_up.eng(prefix:K)} "
format_alt = " $icon $ssid $ip "
interval = 5

[[block]]
block = "sound"

[[block]]
block = "notify"

[[block]]
block = "external_ip"
use_ipv4 = true
format = " $ip $country "

[[block]]
block = "backlight"
device = "intel_backlight"

[[block]]
block = "temperature"
format = " $icon $average "

[[block]]
block = "time"
format = " $timestamp.datetime(f:'%z %e %a %R') "
interval = 60

[icons]
icons = "awesome4"

[theme]
theme = "plain"
