[[block]]
alert = 10.0
block = "disk_space"
info_type = "available"
interval = 60
path = "/"
warning = 20.0

[[block]]
block = "memory"
format = " $icon $mem_used_percents "
format_alt = " $icon_swap $swap_used_percents "

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "net"
format = " $icon {$signal_strength $ssid $ip ^icon_net_down$speed_down.eng(prefix:K) ^icon_net_up$speed_up.eng(prefix:K)} "
interval = 5

# [[block]]
# block = "sound"

# [[block]]
# block = "notify"

[[block]]
block = "time"
format = " $timestamp.datetime(f:'%a %d-%m %R') "
interval = 60

[icons]
icons = "awesome4"

[theme]
theme = "srcery"
